[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 60
healthcheckInterval = 5
startCommand = "node server.js"

[[services]]
http_port = 3000
name = "web"
port = 3000
type = "web"
